### ISSUE TITLE
Doesn't seem to work with IOS

### ISSUE THREAD

**Issue by nospam2k** [audiocogs/audiocogs.github.com#1]
I grabbed the demo setup from audiocogs.org and slightly modified index.html to automatically play a url. This works in Android and Mac Chrome and Safari but not IOS. http://test.u2k.biz/test.htm is my test setup.

**Comment by crackofdusk** [comment]
This is a [known issue](https://github.com/audiocogs/aurora.js/wiki/Known-Issues) and it is not an intended use case for the demo website.

Also see https://github.com/audiocogs/aurora.js/issues/56 and https://github.com/audiocogs/aurora.js/issues/157
